
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Sidebar from "@/components/layout/Sidebar";
import { Toaster } from 'react-hot-toast';
import Providers from "./tanStackQueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-white">
        <Providers>
          <Toaster />

          {/* Fixed Navbar */}
          <header className="fixed top-0 left-0 w-full">
            <Navbar />
          </header>

          {/* Layout */}
          <div className="flex flex-row-reverse pt-16">
            {/* Fixed Sidebar */}
            <aside className="sticky right-0 top-16 h-[calc(100vh-4rem)] w-64">
              <Sidebar />
            </aside>

            {/* Page Content */}
            <main className="w-[calc(100vw-16rem)]">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
